### ISSUE TITLE
import failed

### ISSUE THREAD

**Issue by slmonker** [Slickytail/ComfyUI-InstantX-IPAdapter-SD3#1]
git clone and failed to import, reinstall the requirements still can not import
Total VRAM 24564 MB, total RAM 65367 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 D : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
[Crystools INFO] Crystools version: 1.21.0
[Crystools INFO] CPU: 12th Gen Intel(R) Core(TM) i7-12700KF - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4090 D
[Crystools INFO] NVIDIA Driver: 565.90
Traceback (most recent call last):
  File "O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2031, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantX-IPAdapter-SD3.5L\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantX-IPAdapter-SD3.5L\nodes.py", line 9, in <module>
    from .models.resampler import TimeResampler
ModuleNotFoundError: No module named 'ComfyUI-InstantX-IPAdapter-SD3'

Cannot import O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantX-IPAdapter-SD3.5L module for custom nodes: No module named 'ComfyUI-InstantX-IPAdapter-SD3'
Total VRAM 24564 MB, total RAM 65367 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 D : cudaMallocAsync
### ComfyUI Revision: 2874 [20a560eb] *DETACHED | Released on '2024-11-29'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json### [START] ComfyUI AlekPet Nodes v1.0.35 ###
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Node -> ChatGLMNode: ChatGLM4TranslateCLIPTextEncodeNode, ChatGLM4TranslateTextNode [Loading]
Node -> ArgosTranslateNode: ArgosTranslateCLIPTextEncodeNode, ArgosTranslateTextNode [Loading]
Node -> DeepTranslatorNode: DeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode [Loading] Node -> GoogleTranslateNode: GoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode [Loading]

Node -> PoseNode: PoseNode [Loading]
Node -> ExtrasNode: PreviewTextNode, HexToHueNode, ColorsCorrectNode [Loading]
Node -> IDENode: IDENode [Loading]
Node -> PainterNode: PainterNode [Loading]
### [END] ComfyUI AlekPet Nodes ###

[rgthree-comfy] Loaded 42 fantastic nodes. 🎉

Import times for custom nodes:
   0.0 seconds: O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes
   0.0 seconds: O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Sana
   0.0 seconds: O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds (IMPORT FAILED): O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantX-IPAdapter-SD3.5L
   0.0 seconds: O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper
   0.0 seconds: O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.1 seconds: O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.1 seconds: O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CatvtonFluxWrapper
   0.3 seconds: O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.4 seconds: O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   1.1 seconds: O:\Comfyui test\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet

**Comment by Slickytail** [comment]
Ah, it seems like comfy doesn't properly handle dots in folder names. I'll rename the repo. But you could also rename the folder.

**Comment by slmonker** [comment]
> Ah, it seems like comfy doesn't properly handle dots in folder names. I'll rename the repo. But you could also rename the folder.

rename to ComfyUI-InstantX-IPAdapter-SD3 ,is it?

**Comment by slmonker** [comment]
> Ah, it seems like comfy doesn't properly handle dots in folder names. I'll rename the repo. But you could also rename the folder.
wow dude!it s working!
