### ISSUE TITLE
siglip-so400m-patch14-384.safetensors An error occurs when the siglip-so400m-patch14-384.safetensors file is downloaded

### ISSUE THREAD

**Issue by Nick2024-cmyk** [Slickytail/ComfyUI-InstantX-IPAdapter-SD3#5]
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like siglip-so400m-patch14-384.safetensors is not the path to a directory containing a file named config.json.

Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

Google's clip model, please modify it to be able to manually download it and put it in the local folder, whether the download is forced to download on the Internet, and you can't select the name of the model file, and now the name in the workflow node is fixed and cannot be changed

**Comment by Metal-dude** [comment]
Hi, a solution is proposed here : https://github.com/Slickytail/ComfyUI-InstantX-IPAdapter-SD3/issues/7

**Comment by Slickytail** [comment]
Hello, you will now use the comfy Load Clip Vision/Clip Vision Encode nodes to create the embed, and so you will download the encoder separately. See the example workflow for details
