### ISSUE TITLE
Improvement proposal

### ISSUE THREAD

**Issue by Metal-dude** [Slickytail/ComfyUI-InstantX-IPAdapter-SD3#7]
Hi, 

With the current node implementation, siglip-so400m-patch14-384 is stored in cache\huggingface, which sometimes causes issues (multiple downloads, download interruptions ...).

Just like with https://github.com/Shakker-Labs/ComfyUI-IPAdapter-Flux, it is possible to have the Clip vision model siglip-so400m-patch14-384 stored in ComfyUI_windows_portable\ComfyUI\models\clip (this is the place where Joycaption 2 stores it, so it's possible to use the same model file for both Joycaption 2 and Flux IPAdapter)

For that, in the file nodes.py, you could replace : 

    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "ipadapter": (folder_paths.get_filename_list("ipadapter"),),
                "clip_vision": (["google/siglip-so400m-patch14-384"],),
                "provider": (["cuda", "cpu", "mps"],),
            }
        }

    RETURN_TYPES = ("IP_ADAPTER_SD3_INSTANTX",)
    RETURN_NAMES = ("ipadapter",)
    FUNCTION = "load_model"
    CATEGORY = "InstantXNodes"

    def load_model(self, ipadapter, clip_vision, provider):
        logging.info("Loading InstantX IPAdapter SD3 model.")
        model = SD3IPAdapter(clip_vision, ipadapter, provider)
        return (model,)

with : 

    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "ipadapter": (folder_paths.get_filename_list("ipadapter"),),
                "provider": (["cuda", "cpu", "mps"],),
            }
        }

    RETURN_TYPES = ("IP_ADAPTER_SD3_INSTANTX",)
    RETURN_NAMES = ("ipadapter",)
    FUNCTION = "load_model"
    CATEGORY = "InstantXNodes"

    def load_model(self, ipadapter, provider):
        logging.info("Loading InstantX IPAdapter SD3 model.")
        clip_path = os.path.join(folder_paths.models_dir, "clip", "siglip-so400m-patch14-384")
        model = SD3IPAdapter(clip_path, ipadapter, provider)
        return (model,)
 
That is to say : 

- suppress the line :  "clip_vision": (["google/siglip-so400m-patch14-384"],),
- suppress clip_vision, in load_model 
- suppress clip_vision, in model
- add the line  clip_path = os.path.join(folder_paths.models_dir, "clip", "siglip-so400m-patch14-384")
- add clip_path, in model

Then users have to download the 9 files of the model : https://huggingface.co/google/siglip-so400m-patch14-384/tree/main

and put them in the following directory (for Comfyui portable) : ComfyUI_windows_portable\ComfyUI\models\clip\siglip-so400m-patch14-384

![directory](https://github.com/user-attachments/assets/fc7ab886-5044-4bb0-95fe-756181452a9b)

Then the node is as functional as the original node and won't use cache\huggingface anymore.

This topic is discussed here for ComfyUI-IPAdapter-Flux : https://github.com/Shakker-Labs/ComfyUI-IPAdapter-Flux/issues/46

**Comment by Slickytail** [comment]
I'm very against having users download entire repositories. I've decided instead to just use the siglip model that already has config/code in comfyui. The new example workflow shows how to do it.
It's not the same model as the one before, but it gives very similar results (I suspect that it actually is the same model, but just had some minor surgery on its weights).

**Comment by makisekurisu-jp** [comment]
> I'm very against having users download entire repositories. I've decided instead to just use the siglip model that already has config/code in comfyui. The new example workflow shows how to do it.
> 
> It's not the same model as the one before, but it gives very similar results (I suspect that it actually is the same model, but just had some minor surgery on its weights).

Your adjustment is great and indeed more convenient. In fact, when installing JoyCaption2, siglip-so400m-patch14-384 model was already downloaded. Can you guide me on how to modify the code in ComfyUI-IPAdapter-Flux to achieve the same functionality as your recent update, allowing the use of sigclip_vision_patch14_384.safetensors model?
